# Generated by Django 2.2.6 on 2019-10-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191030_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approved_commment',
            new_name='approved_comment',
        ),
    ]
